//go:build ignore

package main

import (
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	hashes := map[string]string{}
	err := filepath.Walk("integrations", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		// Skip README files — they're documentation, not installable integrations
		if strings.EqualFold(filepath.Base(path), "README.md") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		h := sha256.Sum256(data)
		hashes[path] = fmt.Sprintf("%x", h)
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking integrations: %v\n", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// Code generated by gen_integration_hashes.go; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("var integrationHashes = map[string]string{\n")

	keys := make([]string, 0, len(hashes))
	for k := range hashes {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		b.WriteString(fmt.Sprintf("\t%q: %q,\n", k, hashes[k]))
	}
	b.WriteString("}\n")

	// Format with the current Go version's gofmt so the output is stable
	// regardless of which gofmt version checks it later.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("integration_hashes_gen.go", formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing generated file: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated integration_hashes_gen.go")
}
