// Code generated by gen_integration_hashes.go; DO NOT EDIT.

package main

var integrationHashes = map[string]string{
	"integrations/aider/CONVENTIONS.md":                    "7c8055c71f7377e3fa39a9bf7e0ed2d235a6a6f05a22ad6324fe626d893ab6d0",
	"integrations/claude-code/.claude-plugin/plugin.json":  "3242a897a6de212cf1dba58ce453eec0341c52603b8e17ecc9d3cd99163d1e74",
	"integrations/claude-code/hooks/hooks.json":            "beba2c8bd252637ff31b57ed868e4d56135e1a3f429f872befbd2d34b834512b",
	"integrations/claude-code/skills/crit-cli/SKILL.md":    "d3517450c473b735739ac07b208371826a5496ab7f4e0ec8af9082186cbf5ea8",
	"integrations/claude-code/skills/crit/SKILL.md":        "ecf973b6153c8437e90d54e5c426c231424e3c8e8fd64bc3e58e1504bcc6a450",
	"integrations/cline/crit.md":                           "2ae2d9127309085f4dd600a7e0348cf531b7a1c7847b776fc40a6c2efe250441",
	"integrations/codex/skills/crit-cli/SKILL.md":          "c82320cc11b88f65f8d5ca707e67621edaa647708dfe2cc91089b79e74e1fae0",
	"integrations/codex/skills/crit/SKILL.md":              "fc1148fadbee2c317eaf02a7629d425ebbb1746a24d04bfe81528adbae5a22ec",
	"integrations/cursor/skills/crit-cli/SKILL.md":         "52fc252e6c7131c2bc5fd235427c8b44eb4ae358356cceb2eb319a75479e2187",
	"integrations/cursor/skills/crit/SKILL.md":             "4840c5b25fde68f3c4d31b854dfdab339d11d7f5e36f736a970d7fcd625f1742",
	"integrations/docker/Dockerfile":                       "7657da35225baa2f55e702cae34f80ae62f2e8520d9e84b2aa63cf034b892690",
	"integrations/docker/entrypoint.sh":                    "f53612f5263323423a8ea1cd8c7a4f514ce2ff03ba6f249ca0cf25cf08395dd1",
	"integrations/github-copilot/skills/crit-cli/SKILL.md": "ec91c4238b5b03d0751540b46dd1f31308e95bddd1c7d039faca61f471daed09",
	"integrations/github-copilot/skills/crit/SKILL.md":     "8d7292e4c88a2bdd75abc6ac169bee71620b7a73a162b3e10adbacb53a0b28a9",
	"integrations/opencode/SKILL.md":                       "dd8475916ff3c1803cd28b79ae56ab0bf74a7f343c037a103583552abb8343dd",
	"integrations/opencode/crit.md":                        "98fc3f22f6a8e09ec3951d67957f4627a8214880ee1f3af31d7c2e9a893eebb1",
	"integrations/windsurf/crit.md":                        "1aa51a2b9b7be6e2c03b03b81760b96aeecdda8ffbd59129d2713c0f453d05db",
}
