// Code generated by gen_integration_hashes.go; DO NOT EDIT.

package main

var integrationHashes = map[string]string{
	"integrations/aider/CONVENTIONS.md":                    "6f36029564d015a0b82e3b8899b0f7bbcf95fc88a77dd7b74fa792ca52d3db91",
	"integrations/claude-code/.claude-plugin/plugin.json":  "ccf03fc601e0222bbe27db8e1c480e6acb684f4c1c0c3f7c017137c7efa647dd",
	"integrations/claude-code/hooks/hooks.json":            "beba2c8bd252637ff31b57ed868e4d56135e1a3f429f872befbd2d34b834512b",
	"integrations/claude-code/skills/crit-cli/SKILL.md":    "d3517450c473b735739ac07b208371826a5496ab7f4e0ec8af9082186cbf5ea8",
	"integrations/claude-code/skills/crit/SKILL.md":        "f6e0a264d7215c1caec41add4df898cc13fb0b6e0d6c48087f6a480058557582",
	"integrations/cline/crit.md":                           "baf32ab1ee07634fd5d3973b061a237f24169208756ab963c7f44ad5b892b5ac",
	"integrations/codex/skills/crit-cli/SKILL.md":          "c82320cc11b88f65f8d5ca707e67621edaa647708dfe2cc91089b79e74e1fae0",
	"integrations/codex/skills/crit/SKILL.md":              "99620e42479090f2067b2f7b431b16a21a8b1232575986b7e649dce6b39f9c61",
	"integrations/cursor/skills/crit-cli/SKILL.md":         "52fc252e6c7131c2bc5fd235427c8b44eb4ae358356cceb2eb319a75479e2187",
	"integrations/cursor/skills/crit/SKILL.md":             "b3de0c383f76063a9c966351aa2191be87bb8301c8521489109cfd97005e8a59",
	"integrations/docker/Dockerfile":                       "7657da35225baa2f55e702cae34f80ae62f2e8520d9e84b2aa63cf034b892690",
	"integrations/docker/entrypoint.sh":                    "f53612f5263323423a8ea1cd8c7a4f514ce2ff03ba6f249ca0cf25cf08395dd1",
	"integrations/github-copilot/skills/crit-cli/SKILL.md": "ec91c4238b5b03d0751540b46dd1f31308e95bddd1c7d039faca61f471daed09",
	"integrations/github-copilot/skills/crit/SKILL.md":     "417a647aba071ed4f007bec3b74f5c079cc8a9798d27b9195b97bf54ddbf6851",
	"integrations/opencode/SKILL.md":                       "dd8475916ff3c1803cd28b79ae56ab0bf74a7f343c037a103583552abb8343dd",
	"integrations/opencode/crit.md":                        "45f66ab2b0ae379f352460fcecf0ee21b8fc6d6cbbb5fd257c5a30bcebe01783",
	"integrations/windsurf/crit.md":                        "665bd22f3f287cc57492d2fdf6b90b0c639527dcf54e7b135a3c1c3686157de1",
}
